# Generated by Django 2.2.5 on 2019-10-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('shop', '0006_cart_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='sessions.Session'),
        ),
    ]
